name: First Workflow
on: 
  push: 
    branches:
      - main
jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print a wellcome message
        run: echo "Wellcome to our Github Actions workflow" 

    
      
